version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  app:
    image: csapp:latest
    container_name: csapp
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/csdb?createDatabaseIfNotExist=TRUE
      - SPRING_DATASOURCE_PASSWORD=
    links:
      - mysql_db
    ports:
      - "8081:8081"
